---
name: pagerduty-test
description: Testing pagerduty ticket creation
enabled: true

trigger:
        type: "core.st2.webhook"
        parameters:
            url: "vz-pack-training-internal"

criteria:
  trigger.body.webhookEvent: 
    type: regex
    pattern: "jira:issue_(created|updated)"

action:
    ref: mock_pagerduty.create_ticket
    parameters:
      parameter_body: "{{trigger.body}}"